A API de Produto permite que você liste, visualize, edite e delete produtos.

### Dependências
Para importar um produto, é necessário que tenham sido importadas previamente:

- [Empresas]()
- [Unidades de Medidas]()
- [Opções (cores)]()
- [Opções Item (tamanhos)]()

### Objeto Produto
Um Produto pode ser representado pela seguinte estrutura:

| Atributo                   | Tipo           | Obrigatório | Descrição                                |
|----------------------------|----------------|-------------|------------------------------------------|
| `codigo`                   | string(250)    | Sim         | Código único de identificação do Produto |
| `nome`                     | string(250)    | Sim         | Nome do Produto                          |
| `nomeComercial`            | string(250)    | Sim         | Nome comercial do Produto                |
| `url`                      | string(250)    | Não         | URL externa do Produto                   |
| `observacao`               | longtext       | Não         | Observações referentes ao produto        |
| `peso`                     | decimal(20,5)  | Não         | Peso do produto                          |
| `precoAVista`              | decimal(10,2)  | Não         | Preço à vista do produto                 |
| `precoMinimo`              | decimal(10,2)  | Não         | Preço mínimo do produto                  |
| `precoBase`                | decimal(10,2)  | Não         | Preço base do produto                    |
| `descricaoResumida`        | string(250)    | Não         | Descrição resumida do produto            |
| `descricaoCompleta`        | string(250)    | Não         | Descrição completa do produto            |
| `fichaTecnica`             | string(250)    | Não         | Ficha técnica do produto                 |
| `ncm`                      | string(250)    | Não         | Classificação fiscal do produto          |
| `codigoEmpresa`            | string(250)    | Sim         | Código da Empresa                        |
| `codigoUnidadeMedida`      | string(250)    | Sim         | Código da Unidade de Medida              |
| `codigoGrupoPrincipal`     | string(250)    | Não         | Código do Grupo Principal                |
| `codigoGrupo`              | string(250)    | Não         | Código do Grupo                          |
| `codigoSubgrupoProduto`    | string(250)    | Não         | Código do Subgrupo                       |
| `codigoCategoriaPrincipal` | string(250)    | Não         | Código da Categoria Principal            |
| `codigoCategoria`          | string(250)    | Não         | Código da Categoria                      |
| `codigoSubcategoria`       | string(250)    | Não         | Código da Subcategoria                   |
| `codigoCaracteristicas`    | string(250)[ ] | Não         | Array de códigos das Características     |
| `status`                   | string(250)    | Sim         | Status, Ativo(1) ou Inativo(0)           |

:[Listar Produtos]('./operations/Listar Produtos.apib')

:[Consultar Produto]('./operations/Consultar Produto.apib')

:[Criar Produto]('./operations/Criar Produto.apib')

:[Atualizar Produto]('./operations/Atualizar Produto.apib')

:[Deletar Produto]('./operations/Deletar Produto.apib')