### Atualizar Produto [PATCH /produtos/{codigo}]

+ Parameters
    + codigo (String) ... Código do produto.

+ Request (application/json)

        {
          "codigo": "1",
          "nome": "Produto Multiplier",
          "nomeComercial": "Produto Comercial",
          "url": "produto-multiplier",
          "observacao": "Observação do Produto",
          "peso": 10,
          "precoAVista": 20,
          "precoMinimo": 30,
          "precoBase": 40,
          "descricaoResumida": "Descrição resumida",
          "descricaoCompleta": "Descrição completa do produto",
          "fichaTecnica": "Descrição da ficha técnica do produto",
          "ncm": "52093200",
          "codigoEmpresa": "2",
          "codigoUnidadeMedida": "KG",
          "codigoGrupoPrincipal": "1",
          "codigoGrupo": "1",
          "codigoSubgrupo": "1",
          "codigoCategoriaPrincipal": "1",
          "codigoCategoria": "1",
          "codigoSubcategoria": "1",
          "status": 1
        }

+ Response 200 (application/json)

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }