on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        - uses: actions/checkout@v2
        - run: yarn --production
        - run: yarn build
  
  deploy:
    name: Deploy to Apiary
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Commit
        - run: git add apiary.apib
        - run: git commit -m "v$(node -p "require('./package.json').version")"
        
      - name: Push to main
        - run: git push origin main