on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Deploy
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: node:alpine

    steps:
      - name: Update Git
        run: apk add git --update-cache

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build
        run: |
          npm install --only=production
          chown -R $USER:$USER .
          npm run build
      
      - name: Commit & Push
        run: |
          git add apiary.apib
          git commit -m "v$(node -p "require('./package.json').version")"
          git push origin main