on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build & Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: node:alpine

    steps:
      - name: Update Git
        run: apk add git --update-cache

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build
        run: |
          npm ci
          npm run build
      
      - name: Commit & Push
        run: |
          git add apiary.apib
          git commit -m "v$(node -p "require('./package.json').version")"
          git push origin main