on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          yarn --production
          run: yarn build
  
  deploy:
    name: Deploy to Apiary
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Commit & Push
        run: |
          git add apiary.apib
          git commit -m "v$(node -p "require('./package.json').version")"
          git push origin main